export const PRODUCT_FETCH_ALL = "PRODUCT_FETCH_ALL"
export const PRODUCT_FETCH_ALL_FAILED = "PRODUCT_FETCH_ALL_FAILED"

export const PRODUCT_FETCH_SINGLE = "PRODUCT_FETCH_SINGLE"
export const PRODUCT_FETCH_SINGLE_FAILED = "PRODUCT_FETCH_SINGLE_FAILED"
